name: Yad2 Car Scraper

on:
  schedule:
    # Run every hour from 08:00 to 24:00 Israel time (5:00-21:00 UTC)
    - cron: '0 5-21 * * *'  # Every hour from 5 UTC to 21 UTC (8 AM to 12 AM Israel time)
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the workflow to commit back to repo
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install Chrome for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    
    - name: Check if within active hours
      id: check-time
      run: |
        # Get current time in Israel timezone
        ISRAEL_HOUR=$(TZ='Asia/Jerusalem' date +'%H')
        echo "Current Israel hour: $ISRAEL_HOUR"
        
        # Check if it's within active hours (8 AM to 12 AM = 8-23)
        if [ "$ISRAEL_HOUR" -ge 8 ] && [ "$ISRAEL_HOUR" -le 23 ]; then
          echo "Within active hours (8 AM - 12 AM) - running scraper"
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "Outside active hours - sleeping"  
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run scraper
      if: steps.check-time.outputs.should_run == 'true'
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: npm run github-action
    
    - name: Commit persistence data
      if: steps.check-time.outputs.should_run == 'true'
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add the updated listings.json if it changed
        git add data/listings.json
        
        # Commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to persistence data"
        else
          git commit -m "Update car listings - $(date '+%Y-%m-%d %H:%M UTC')"
          git push
          echo "Committed updated persistence data"
        fi
    
    - name: Sleep message
      if: steps.check-time.outputs.should_run == 'false'
      run: |
        ISRAEL_TIME=$(TZ='Asia/Jerusalem' date +'%H:%M')
        echo "😴 Sleeping... Current Israel time: $ISRAEL_TIME (Active: 8 AM - 12 AM)"