name: Yad2 Car Scraper

on:
  schedule:
    # Run only during peak notification times (Israel time)
    # 9 AM, 1 PM, 6 PM, 10 PM Israel time
    - cron: '0 6,10,15,19 * * *'  # Peak hours (UTC times)
    # Test run at 9:20 AM Israel time (6:20 UTC)
    - cron: '20 6 * * *'  # Test run
    # Keep repo active to prevent workflow disabling
    - cron: '0 12 * * *'  # Daily keepalive at noon UTC
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the workflow to commit back to repo
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check if within notification hours
      id: check-time
      run: |
        # Get current time in Israel timezone
        ISRAEL_HOUR=$(TZ='Asia/Jerusalem' date +'%H')
        echo "Current Israel hour: $ISRAEL_HOUR"
        
        # Check if it's a peak notification hour (9, 13, 18, 22)
        if [ "$ISRAEL_HOUR" -eq 9 ] || [ "$ISRAEL_HOUR" -eq 13 ] || [ "$ISRAEL_HOUR" -eq 18 ] || [ "$ISRAEL_HOUR" -eq 22 ]; then
          echo "Peak notification hour - sending updates"
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "Not a peak hour - silent scan"  
          echo "should_run=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Run scraper
      if: steps.check-time.outputs.should_run == 'true'
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: npm run github-action
    
    - name: Commit persistence data
      if: steps.check-time.outputs.should_run == 'true'
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add the updated last-seen.json if it changed
        git add data/last-seen.json
        
        # Commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to persistence data"
        else
          git commit -m "Update last-seen listings - $(date '+%Y-%m-%d %H:%M UTC')"
          git push
          echo "Committed updated persistence data"
        fi
    
    - name: Sleep message
      if: steps.check-time.outputs.should_run == 'false'
      run: |
        ISRAEL_TIME=$(TZ='Asia/Jerusalem' date +'%H:%M')
        echo "😴 Sleeping... Current Israel time: $ISRAEL_TIME (Active: 8 AM - 12 AM)"