name: Yad2 Car Scraper

on:
  schedule:
    # Run every 15 minutes during active hours (8 AM - 12 AM Israel time)
    # Israel is UTC+2 (winter) or UTC+3 (summer)
    # So 8 AM Israel = 6 AM UTC (winter) / 5 AM UTC (summer)
    # 12 AM Israel = 10 PM UTC (winter) / 9 PM UTC (summer)
    # We'll use UTC times and check Israel time in the script
    - cron: '*/15 * * * *'  # Every 15 minutes
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check if within active hours (8 AM - 12 AM Israel time)
      id: check-time
      run: |
        # Get current time in Israel timezone
        ISRAEL_HOUR=$(TZ='Asia/Jerusalem' date +'%H')
        echo "Current Israel hour: $ISRAEL_HOUR"
        
        # Check if between 8 AM (08) and 11 PM (23) or exactly midnight (00)
        if [ "$ISRAEL_HOUR" -ge 8 ] || [ "$ISRAEL_HOUR" -eq 0 ]; then
          echo "Within active hours (8 AM - 12 AM)"
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "Outside active hours - sleeping"
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run scraper
      if: steps.check-time.outputs.should_run == 'true'
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: npm run github-action
    
    - name: Sleep message
      if: steps.check-time.outputs.should_run == 'false'
      run: |
        ISRAEL_TIME=$(TZ='Asia/Jerusalem' date +'%H:%M')
        echo "😴 Sleeping... Current Israel time: $ISRAEL_TIME (Active: 8 AM - 12 AM)"